### ISSUE TITLE
Replace progress bars with icons in certain cases

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-pageLevelProgress#181]
### Subject of the enhancement
In the PLP drawer, component completion is only represented by two states: "incomplete" or "complete". Presentation components like Accordion do not show partial completion when, for example, one of three items have been visited. The progress bar is either empty (incomplete) or full (complete).

If we were to switch the component progress bars to completion icons, this may increase the user's comprehension of what has been completed and what is still left. Furthermore, a lock icon could be used to indicate a locked state.

This could be a new, configurable option or we could replace the current behavior entirely.

### Drawer example
<img src="https://user-images.githubusercontent.com/898168/234932060-78880310-ecc2-46bc-8d40-c277bdfcf975.jpg" width="300">
<img src="https://user-images.githubusercontent.com/898168/234931456-73c1d833-ca6e-4ec1-aa65-4be574b76704.jpg" width="300">

### Component title example
<img src="https://user-images.githubusercontent.com/898168/234931350-2227fd6b-b285-4232-a297-cb9cf10b4bfb.jpg" width="500">
<img src="https://user-images.githubusercontent.com/898168/234931381-fd6004e4-94b4-4eab-af04-af91d6e4a7ce.jpg" width="500">

**Comment by oliverfoster** [comment]
I like the locked icons.

It is possible to use non-binary/continuous indicator bars for itemscomponent models if we want.

I'm not sure about the title ticks and plp ticks, as we will need continuous bars for some things, like pages and menus and plp nav icon etc. and because I always think of ticks and crosses an an axiom for correctness. Although I do understand we now use them for hotgraphic visited states, which I do like.

**Comment by swashbuck** [comment]
Thanks, @oliverfoster . Just to clarify, I wouldn't recommend changing the progress bars to icons on the PLP nav button, the menu items, or for content objects (except for "locked" states as shown above).

**Comment by StuartNicholls** [comment]
What happens when the page nav bar is filled? no tick? tick appears?

Side note, the default look of the process bar could do with a transparent border around the progress so it separates it visually from the white border. This helps make it look a bit more like a progress bar. Can be a pain point with clients.

<img width="320" alt="Screenshot 2023-04-27 at 18 41 48" src="https://user-images.githubusercontent.com/6065360/234946856-6f0bf05b-489b-4a47-b748-f3cac1355c0f.png">

**Comment by swashbuck** [comment]
@StuartNicholls Agree on the transparent border for sure. Did you want to create a new ticket for that?

Hmm, I think we could do a tick for a 100% completed page, too. I could go either way on this one, though.

**Comment by StuartNicholls** [comment]
I think we could sneak the border in as its so minor if we get to a consensus on this.  If a problem, yeah Ill sort it later. 

I think the progress with a tick works - Im sure Ive done that before. Kind of brings progress and tick as a completed status together. Just conscious of space / visual clutter. I could go either way also

**Comment by oliverfoster** [comment]
Transparent border, with that initial fill looks great.

**Comment by swashbuck** [comment]
The lock icon has been added in #210. We can also use this new `.icon` element to show a completion checkmark via theme customization.

From my perspective, the only thing left would be to add an `.icon` element to the component title PLPs so that we can show a checkmark. We can actually do this with theme work, although it won't be a dedicated icon element that has an `aria-hidden="true"`. We rarely (if ever) use this feature, so I'm less concerned about it.

Otherwise, should we close out this ticket?

@StuartNicholls , are you fine to create a new ticket regarding the transparent border you mentioned above?

**Comment by oliverfoster** [comment]
> @StuartNicholls , are you fine to create a new ticket regarding the transparent border you mentioned above?

Issue here https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/issues/217
